export const product:Product = {
  nombre: '',
  imagen: '',
  descripcion: '',
  impuesto:0,
  codigo: '',
  precio_dolar: '',
  referencia: 0,
  id: 0,
  adm_conceptos_id:0,
  cantidad: 0,
  precio_a: 0,
  precio_b: 0,
  precio_c: 0,
  adm_empresa_id: 0,
  talla: '',
  color: '',
  descuento: '',
  serial_estatico: 0,
  serial_dinamico: 0,
  existencia_minima: '',
  existencia_maxima: '',
  adm_tipos_conceptos_id: 0,
  adm_ubicacion_id: 0,
  costo: 0,
  ultimo_costo: '',
  costo_mayor: '',
  costo_promedio: '',
  fecha_at: '',
  fecha_in: '',
  fecha_uc: '',
  adm_grupos_id: 0,
  adm_subgrupos_id: 0,
  empaque:"",
  oferta:0,
  uso:"",
  presentacion: '',
  adm_unidades_id: 0,
  fecha_hora: 0,
  adm_marcas_id: 0,
  estado:  0,
  pvp: '',
  utilidad: '',
  utilidad_a: '',
  utilidad_b: '',
  utilidad_c: '',
  utilidad_dolar: '',
  costo_dolar: '',
  precio_variable: 0,
  retiene:  0,
  farm_principio_activo_id: 0,
  costo_adicional: '',
  costo_adicional2: '',
  cant_ensamblado: '',
  licor:  0,
  porcentaje: 0,
  visible_pv:  0,
  visible_web:  0,
  rest_areas_id: 0,
  setcortesia:  0,
  exento:  0,
  merma:  0,
  existencia_c: 0,
  obviar_ajuste:  0,
  iva:  0,
}

export const clienteDefault:Cliente = {
  img: "",
  nombre: "",
  id: 0,
  telefono: "",
  Rif: "",
  direccion: "",
  cedula:"",
  limite_credito:0,
  telefono_contacto:"",
  nombre_comercial: "",
}