const Factura = {
  name: 'factura',
  properties: {
    id: 'int?',
    numero_factura: 'string?',
    numero_fiscal: 'string?',
    serial_impresora: 'string?',
    fecha_at: 'string?',
    fecha_in: 'string?',
    adm_vendedor_id: 'int?',
    adm_clientes_id: 'int?',
    subtotal: 'string?',
    subtotal_dolar: 'string?',
    iva: 'string?',
    iva_dolar: 'string?',
    facturado: 'int?',
    estatus_pago: 'int?',
    abono: 'string?',
    abono_dolar: 'string?',
    adm_tipos_facturas_id: 'int?',
    adm_usuarios_id: 'int?',
    adm_caja_id: 'int?',
    observacion: 'string?',
    adm_enc_presupuesto_id: 'int?',
    anulada: 'int?',
    usuario_modificador: 'string?',
    devuelto: 'string?',
    motivoreimpresion: 'string?',
    descuento_dolar: 'string?',
    afecta_factura: 'string?',
    rest_pedidos_id: 'int?',
    fecha_hora: 'string?',
    coo: 'string?',
    estatus_entrega: 'int?',
    fecha_entrega: 'string?',
    detalles: 'detalleFactura[]',
  },
};
const DetalleFactura = {
  name: 'detalleFactura',
  properties: {
    id: 'int?',
    adm_enc_facturas_id: 'int?',
    adm_conceptos_id: 'int?',
    adm_vendedor_id: 'int?',
    costo: 'string?',
    costo_dolar: 'string?',
    precio: 'string?',
    precio_dolar: 'string?',
    descuentopro: 'string?',
    fecha_at: 'string?',
    cantidad: 'string?',
    despachado: 'int?',
    devuelto: 'int?',
    adm_seriales_id: 'int?',
    monto_documento: 'string?',
    adm_lotes_id: 'int?',
  },
};
const TFacturaSchema = {
  name: 'TFactura',
  properties: {
    id: 'int',
    nombre: 'string?',
    inicial: 'string?',
  },
};
export default {Factura, DetalleFactura, TFacturaSchema};
